version: '3'
services:
  hello:
    build: ./app
    expose:
      - 8080
    ports:
      - "8080:8080"
  nginx:
    image: nginx:1.16-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

